import { pgTable, unique, integer, varchar, timestamp, doublePrecision, boolean, real, text } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const locations = pgTable("locations", {
	id: integer(),
	host: varchar({ length: 16 }),
	beginAt: timestamp("begin_at", { mode: 'string' }),
	endAt: timestamp("end_at", { mode: 'string' }),
	login: varchar({ length: 16 }),
	userId: integer("user_id"),
	duration: integer(),
}, (table) => [
	unique("locations_id_key").on(table.id),
]);

export const piscineThreeProjects = pgTable("piscine_three_projects", {
	login: varchar({ length: 8 }),
	shell00: integer("shell_00"),
	shell01: integer("shell_01"),
	c00: integer("c_00"),
	c01: integer("c_01"),
	exam00: integer("exam_00"),
	rush00: integer("rush_00"),
	c02: integer("c_02"),
	c03: integer("c_03"),
	c04: integer("c_04"),
	c05: integer("c_05"),
	exam01: integer("exam_01"),
	rush01: integer("rush_01"),
	c06: integer("c_06"),
	c07: integer("c_07"),
	c08: integer("c_08"),
	c09: integer("c_09"),
	c10: integer("c_10"),
	c11: integer("c_11"),
	exam02: integer("exam_02"),
	rush02: integer("rush_02"),
	c12: integer("c_12"),
	c13: integer("c_13"),
	bsq: integer(),
	finalExam: integer("final_exam"),
}, (table) => [
	unique("piscine_three_projects_login_key").on(table.login),
]);

export const cursusUsersPace = pgTable("cursus_users_pace", {
	cursusUserId: integer("cursus_user_id"),
	login: varchar({ length: 16 }),
	milestone: integer(),
	deadline: timestamp({ mode: 'string' }),
	pace: integer(),
}, (table) => [
	unique("cursus_users_pace_cursus_user_id_key").on(table.cursusUserId),
]);

export const piscineJulyLocations = pgTable("piscine_july_locations", {
	login: varchar({ length: 8 }),
	jun19: doublePrecision(),
	jun20: doublePrecision(),
	jun21: doublePrecision(),
	jun22: doublePrecision(),
	jun23: doublePrecision(),
	jun24: doublePrecision(),
	jun25: doublePrecision(),
	jun26: doublePrecision(),
	jun27: doublePrecision(),
	jun28: doublePrecision(),
	jun29: doublePrecision(),
	jun30: doublePrecision(),
	jul01: doublePrecision(),
	jul02: doublePrecision(),
	jul03: doublePrecision(),
	jul04: doublePrecision(),
	jul05: doublePrecision(),
	jul06: doublePrecision(),
	jul07: doublePrecision(),
	jul08: doublePrecision(),
	jul09: doublePrecision(),
	jul10: doublePrecision(),
	jul11: doublePrecision(),
	jul12: doublePrecision(),
	jul13: doublePrecision(),
	jul14: doublePrecision(),
}, (table) => [
	unique("piscine_july_locations_login_key").on(table.login),
]);

export const users = pgTable("users", {
	id: integer(),
	login: varchar({ length: 16 }),
	kind: varchar({ length: 16 }),
	firstName: varchar("first_name", { length: 64 }),
	lastName: varchar("last_name", { length: 64 }),
	email: varchar({ length: 320 }),
	poolMonth: varchar("pool_month", { length: 320 }),
	poolYear: varchar("pool_year", { length: 320 }),
	createdAt: timestamp("created_at", { mode: 'string' }),
	updatedAt: timestamp("updated_at", { mode: 'string' }),
	wallet: integer(),
	correctionPoints: integer("correction_points"),
	team: integer(),
	teamLeader: boolean("team_leader"),
}, (table) => [
	unique("users_id_key").on(table.id),
]);

export const piscineFourProjects = pgTable("piscine_four_projects", {
	login: varchar({ length: 8 }),
	shell00: integer("shell_00"),
	shell01: integer("shell_01"),
	c00: integer("c_00"),
	c01: integer("c_01"),
	exam00: integer("exam_00"),
	rush00: integer("rush_00"),
	c02: integer("c_02"),
	c03: integer("c_03"),
	c04: integer("c_04"),
	c05: integer("c_05"),
	exam01: integer("exam_01"),
	rush01: integer("rush_01"),
	c06: integer("c_06"),
	c07: integer("c_07"),
	c08: integer("c_08"),
	c09: integer("c_09"),
	c10: integer("c_10"),
	c11: integer("c_11"),
	exam02: integer("exam_02"),
	rush02: integer("rush_02"),
	c12: integer("c_12"),
	c13: integer("c_13"),
	bsq: integer(),
	finalExam: integer("final_exam"),
}, (table) => [
	unique("piscine_four_projects_login_key").on(table.login),
]);

export const cursusUsers = pgTable("cursus_users", {
	id: integer(),
	userId: integer("user_id"),
	cursusId: integer("cursus_id"),
	login: varchar({ length: 16 }),
	level: real(),
	createdAt: timestamp("created_at", { mode: 'string' }),
	updatedAt: timestamp("updated_at", { mode: 'string' }),
	beginAt: timestamp("begin_at", { mode: 'string' }),
	endAt: timestamp("end_at", { mode: 'string' }),
	blackholedAt: timestamp("blackholed_at", { mode: 'string' }),
}, (table) => [
	unique("cursus_users_id_key").on(table.id),
]);

export const piscineFourLogtimes = pgTable("piscine_four_logtimes", {
	login: varchar({ length: 8 }),
	apr01: doublePrecision(),
	apr02: doublePrecision(),
	apr03: doublePrecision(),
	apr04: doublePrecision(),
	apr05: doublePrecision(),
	apr06: doublePrecision(),
	apr07: doublePrecision(),
	apr08: doublePrecision(),
	apr09: doublePrecision(),
	apr10: doublePrecision(),
	apr11: doublePrecision(),
	apr12: doublePrecision(),
	apr13: doublePrecision(),
	apr14: doublePrecision(),
	apr15: doublePrecision(),
	apr16: doublePrecision(),
	apr17: doublePrecision(),
	apr18: doublePrecision(),
	apr19: doublePrecision(),
	apr20: doublePrecision(),
	apr21: doublePrecision(),
	apr22: doublePrecision(),
	apr23: doublePrecision(),
	apr24: doublePrecision(),
	apr25: doublePrecision(),
	apr26: doublePrecision(),
}, (table) => [
	unique("piscine_four_logtimes_login_key").on(table.login),
]);

export const piscineJulyProjects = pgTable("piscine_july_projects", {
	login: varchar({ length: 8 }),
	shell00: integer("shell_00"),
	shell01: integer("shell_01"),
	c00: integer("c_00"),
	c01: integer("c_01"),
	exam00: integer("exam_00"),
	rush00: integer("rush_00"),
	c02: integer("c_02"),
	c03: integer("c_03"),
	c04: integer("c_04"),
	c05: integer("c_05"),
	exam01: integer("exam_01"),
	rush01: integer("rush_01"),
	c06: integer("c_06"),
	c07: integer("c_07"),
	c08: integer("c_08"),
	c09: integer("c_09"),
	c10: integer("c_10"),
	c11: integer("c_11"),
	exam02: integer("exam_02"),
	rush02: integer("rush_02"),
	c12: integer("c_12"),
	c13: integer("c_13"),
	bsq: integer(),
	finalExam: integer("final_exam"),
}, (table) => [
	unique("piscine_july_projects_login_key").on(table.login),
]);

export const closes = pgTable("closes", {
	id: integer(),
	reason: text(),
	state: varchar({ length: 32 }),
	kind: varchar({ length: 32 }),
	endAt: timestamp("end_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }),
	updatedAt: timestamp("updated_at", { mode: 'string' }),
	login: varchar({ length: 8 }),
	closerLogin: varchar("closer_login", { length: 8 }),
	cServiceDuration: varchar("c_service_duration", { length: 32 }),
}, (table) => [
	unique("closes_id_key").on(table.id),
]);

export const studentsLogtime = pgTable("students_logtime", {
	login: varchar({ length: 8 }),
	sep05: doublePrecision(),
	sep06: doublePrecision(),
	sep07: doublePrecision(),
	sep08: doublePrecision(),
	sep09: doublePrecision(),
	sep10: doublePrecision(),
	sep11: doublePrecision(),
	sep12: doublePrecision(),
	sep13: doublePrecision(),
	sep14: doublePrecision(),
	sep15: doublePrecision(),
	sep16: doublePrecision(),
	sep17: doublePrecision(),
	sep18: doublePrecision(),
	sep19: doublePrecision(),
	sep20: doublePrecision(),
	sep21: doublePrecision(),
	sep22: doublePrecision(),
	sep23: doublePrecision(),
	sep24: doublePrecision(),
	sep25: doublePrecision(),
	sep26: doublePrecision(),
	sep27: doublePrecision(),
	sep28: doublePrecision(),
	sep29: doublePrecision(),
	sep30: doublePrecision(),
	oct01: doublePrecision(),
	oct02: doublePrecision(),
	oct03: doublePrecision(),
	oct04: doublePrecision(),
	oct05: doublePrecision(),
	oct06: doublePrecision(),
	oct07: doublePrecision(),
	oct08: doublePrecision(),
	oct09: doublePrecision(),
	oct10: doublePrecision(),
	oct11: doublePrecision(),
	oct12: doublePrecision(),
	oct13: doublePrecision(),
	oct14: doublePrecision(),
	oct15: doublePrecision(),
	oct16: doublePrecision(),
	oct17: doublePrecision(),
	oct18: doublePrecision(),
	oct19: doublePrecision(),
	oct20: doublePrecision(),
	oct21: doublePrecision(),
	oct22: doublePrecision(),
	oct23: doublePrecision(),
	oct24: doublePrecision(),
	oct25: doublePrecision(),
	oct26: doublePrecision(),
	oct27: doublePrecision(),
	oct28: doublePrecision(),
	oct29: doublePrecision(),
	oct30: doublePrecision(),
	oct31: doublePrecision(),
	nov01: doublePrecision(),
	nov02: doublePrecision(),
	nov03: doublePrecision(),
	nov04: doublePrecision(),
	nov05: doublePrecision(),
	nov06: doublePrecision(),
	nov07: doublePrecision(),
	nov08: doublePrecision(),
	nov09: doublePrecision(),
	nov10: doublePrecision(),
	nov11: doublePrecision(),
	nov12: doublePrecision(),
	nov13: doublePrecision(),
	nov14: doublePrecision(),
	nov15: doublePrecision(),
	nov16: doublePrecision(),
	nov17: doublePrecision(),
	nov18: doublePrecision(),
	nov19: doublePrecision(),
	nov20: doublePrecision(),
	nov21: doublePrecision(),
	nov22: doublePrecision(),
	nov23: doublePrecision(),
	nov24: doublePrecision(),
	nov25: doublePrecision(),
	nov26: doublePrecision(),
	nov27: doublePrecision(),
	nov28: doublePrecision(),
	nov29: doublePrecision(),
	nov30: doublePrecision(),
	dec01: doublePrecision(),
	dec02: doublePrecision(),
	dec03: doublePrecision(),
	dec04: doublePrecision(),
	dec05: doublePrecision(),
	dec06: doublePrecision(),
	dec07: doublePrecision(),
	dec08: doublePrecision(),
	dec09: doublePrecision(),
	dec10: doublePrecision(),
	dec11: doublePrecision(),
	dec12: doublePrecision(),
	dec13: doublePrecision(),
	dec14: doublePrecision(),
	dec15: doublePrecision(),
	dec16: doublePrecision(),
	dec17: doublePrecision(),
	dec18: doublePrecision(),
	dec19: doublePrecision(),
	dec20: doublePrecision(),
	dec21: doublePrecision(),
	dec22: doublePrecision(),
	dec23: doublePrecision(),
	dec24: doublePrecision(),
	dec25: doublePrecision(),
	dec26: doublePrecision(),
	dec27: doublePrecision(),
	dec28: doublePrecision(),
	dec29: doublePrecision(),
	dec30: doublePrecision(),
	dec31: doublePrecision(),
}, (table) => [
	unique("students_logtime_login_key").on(table.login),
]);

export const piscineAugustLocations = pgTable("piscine_august_locations", {
	login: varchar({ length: 8 }),
	jul24: doublePrecision(),
	jul25: doublePrecision(),
	jul26: doublePrecision(),
	jul27: doublePrecision(),
	jul28: doublePrecision(),
	jul29: doublePrecision(),
	jul30: doublePrecision(),
	jul31: doublePrecision(),
	aug01: doublePrecision(),
	aug02: doublePrecision(),
	aug03: doublePrecision(),
	aug04: doublePrecision(),
	aug05: doublePrecision(),
	aug06: doublePrecision(),
	aug07: doublePrecision(),
	aug08: doublePrecision(),
	aug09: doublePrecision(),
	aug10: doublePrecision(),
	aug11: doublePrecision(),
	aug12: doublePrecision(),
	aug13: doublePrecision(),
	aug14: doublePrecision(),
	aug15: doublePrecision(),
	aug16: doublePrecision(),
	aug17: doublePrecision(),
	aug18: doublePrecision(),
}, (table) => [
	unique("piscine_august_locations_login_key").on(table.login),
]);

export const studentsProjects = pgTable("students_projects", {
	login: varchar({ length: 8 }),
	libft: integer(),
	ftPrintf: integer("ft_printf"),
	getNextLine: integer("get_next_line"),
	born2Beroot: integer(),
	pushSwap: integer("push_swap"),
	examRank02: integer("exam_rank_02"),
	minitalk: integer(),
	pipex: integer(),
	soLong: integer("so_long"),
	fdf: integer(),
	fractOl: integer("fract_ol"),
	minishell: integer(),
	philosophers: integer(),
	examRank03: integer("exam_rank_03"),
	minirt: integer(),
	cub3D: integer(),
	netpractice: integer(),
	cppModule04: integer("cpp_module_04"),
	examRank04: integer("exam_rank_04"),
	inception: integer(),
	ftIrc: integer("ft_irc"),
	webserv: integer(),
	cppModule09: integer("cpp_module_09"),
	examRank05: integer("exam_rank_05"),
	ftTranscendence: integer("ft_transcendence"),
	examRank06: integer("exam_rank_06"),
}, (table) => [
	unique("students_projects_login_key").on(table.login),
]);

export const piscineAugustProjects = pgTable("piscine_august_projects", {
	login: varchar({ length: 8 }),
	shell00: integer("shell_00"),
	shell01: integer("shell_01"),
	c00: integer("c_00"),
	c01: integer("c_01"),
	exam00: integer("exam_00"),
	rush00: integer("rush_00"),
	c02: integer("c_02"),
	c03: integer("c_03"),
	c04: integer("c_04"),
	c05: integer("c_05"),
	exam01: integer("exam_01"),
	rush01: integer("rush_01"),
	c06: integer("c_06"),
	c07: integer("c_07"),
	c08: integer("c_08"),
	c09: integer("c_09"),
	c10: integer("c_10"),
	c11: integer("c_11"),
	exam02: integer("exam_02"),
	rush02: integer("rush_02"),
	c12: integer("c_12"),
	c13: integer("c_13"),
	bsq: integer(),
	finalExam: integer("final_exam"),
}, (table) => [
	unique("piscine_august_projects_login_key").on(table.login),
]);

export const piscineThreeLogtimes = pgTable("piscine_three_logtimes", {
	login: varchar({ length: 8 }),
	feb26: doublePrecision(),
	feb27: doublePrecision(),
	feb28: doublePrecision(),
	feb29: doublePrecision(),
	mar01: doublePrecision(),
	mar02: doublePrecision(),
	mar03: doublePrecision(),
	mar04: doublePrecision(),
	mar05: doublePrecision(),
	mar06: doublePrecision(),
	mar07: doublePrecision(),
	mar08: doublePrecision(),
	mar09: doublePrecision(),
	mar10: doublePrecision(),
	mar11: doublePrecision(),
	mar12: doublePrecision(),
	mar13: doublePrecision(),
	mar14: doublePrecision(),
	mar15: doublePrecision(),
	mar16: doublePrecision(),
	mar17: doublePrecision(),
	mar18: doublePrecision(),
	mar19: doublePrecision(),
	mar20: doublePrecision(),
	mar21: doublePrecision(),
	mar22: doublePrecision(),
}, (table) => [
	unique("piscine_three_logtimes_login_key").on(table.login),
]);
